// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/geo/v1/geo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IpRequest는 IP 주소를 포함하는 요청 메시지입니다
type IpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpRequest) Reset() {
	*x = IpRequest{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpRequest) ProtoMessage() {}

func (x *IpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpRequest.ProtoReflect.Descriptor instead.
func (*IpRequest) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{0}
}

func (x *IpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// GeoDataResponse는 종합적인 지리 정보를 포함하는 응답 메시지입니다
type GeoDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IpAddress      string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	City           string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode    string                 `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CountryName    string                 `protobuf:"bytes,4,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	ContinentCode  string                 `protobuf:"bytes,5,opt,name=continent_code,json=continentCode,proto3" json:"continent_code,omitempty"`
	Latitude       float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TimeZone       string                 `protobuf:"bytes,8,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	Asn            uint32                 `protobuf:"varint,9,opt,name=asn,proto3" json:"asn,omitempty"`
	Isp            string                 `protobuf:"bytes,10,opt,name=isp,proto3" json:"isp,omitempty"`
	IsValid        bool                   `protobuf:"varint,11,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	IsAnonymous    bool                   `protobuf:"varint,12,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	IsAnonymousVpn bool                   `protobuf:"varint,13,opt,name=is_anonymous_vpn,json=isAnonymousVpn,proto3" json:"is_anonymous_vpn,omitempty"`
	IsTorExitNode  bool                   `protobuf:"varint,14,opt,name=is_tor_exit_node,json=isTorExitNode,proto3" json:"is_tor_exit_node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GeoDataResponse) Reset() {
	*x = GeoDataResponse{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoDataResponse) ProtoMessage() {}

func (x *GeoDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoDataResponse.ProtoReflect.Descriptor instead.
func (*GeoDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{1}
}

func (x *GeoDataResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GeoDataResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoDataResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GeoDataResponse) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *GeoDataResponse) GetContinentCode() string {
	if x != nil {
		return x.ContinentCode
	}
	return ""
}

func (x *GeoDataResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoDataResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoDataResponse) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *GeoDataResponse) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *GeoDataResponse) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *GeoDataResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *GeoDataResponse) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *GeoDataResponse) GetIsAnonymousVpn() bool {
	if x != nil {
		return x.IsAnonymousVpn
	}
	return false
}

func (x *GeoDataResponse) GetIsTorExitNode() bool {
	if x != nil {
		return x.IsTorExitNode
	}
	return false
}

// CityResponse는 도시 정보를 포함하는 응답 메시지입니다
type CityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          *CityInfo              `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       *CountryInfo           `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Continent     *ContinentInfo         `protobuf:"bytes,3,opt,name=continent,proto3" json:"continent,omitempty"`
	Location      *LocationInfo          `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityResponse) Reset() {
	*x = CityResponse{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityResponse) ProtoMessage() {}

func (x *CityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityResponse.ProtoReflect.Descriptor instead.
func (*CityResponse) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{2}
}

func (x *CityResponse) GetCity() *CityInfo {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *CityResponse) GetCountry() *CountryInfo {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *CityResponse) GetContinent() *ContinentInfo {
	if x != nil {
		return x.Continent
	}
	return nil
}

func (x *CityResponse) GetLocation() *LocationInfo {
	if x != nil {
		return x.Location
	}
	return nil
}

// CountryResponse는 국가 정보를 포함하는 응답 메시지입니다
type CountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       *CountryInfo           `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Continent     *ContinentInfo         `protobuf:"bytes,2,opt,name=continent,proto3" json:"continent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryResponse) Reset() {
	*x = CountryResponse{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryResponse) ProtoMessage() {}

func (x *CountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryResponse.ProtoReflect.Descriptor instead.
func (*CountryResponse) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{3}
}

func (x *CountryResponse) GetCountry() *CountryInfo {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *CountryResponse) GetContinent() *ContinentInfo {
	if x != nil {
		return x.Continent
	}
	return nil
}

// ASNResponse는 ASN 정보를 포함하는 응답 메시지입니다
type ASNResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	AutonomousSystemNumber       uint32                 `protobuf:"varint,1,opt,name=autonomous_system_number,json=autonomousSystemNumber,proto3" json:"autonomous_system_number,omitempty"`
	AutonomousSystemOrganization string                 `protobuf:"bytes,2,opt,name=autonomous_system_organization,json=autonomousSystemOrganization,proto3" json:"autonomous_system_organization,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ASNResponse) Reset() {
	*x = ASNResponse{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASNResponse) ProtoMessage() {}

func (x *ASNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASNResponse.ProtoReflect.Descriptor instead.
func (*ASNResponse) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{4}
}

func (x *ASNResponse) GetAutonomousSystemNumber() uint32 {
	if x != nil {
		return x.AutonomousSystemNumber
	}
	return 0
}

func (x *ASNResponse) GetAutonomousSystemOrganization() string {
	if x != nil {
		return x.AutonomousSystemOrganization
	}
	return ""
}

// AnonymousResponse는 익명 IP 확인 결과를 포함하는 응답 메시지입니다
type AnonymousResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsAnonymous    bool                   `protobuf:"varint,1,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	IsTorExitNode  bool                   `protobuf:"varint,2,opt,name=is_tor_exit_node,json=isTorExitNode,proto3" json:"is_tor_exit_node,omitempty"`
	FeatureSupport bool                   `protobuf:"varint,3,opt,name=feature_support,json=featureSupport,proto3" json:"feature_support,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnonymousResponse) Reset() {
	*x = AnonymousResponse{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymousResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymousResponse) ProtoMessage() {}

func (x *AnonymousResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymousResponse.ProtoReflect.Descriptor instead.
func (*AnonymousResponse) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{5}
}

func (x *AnonymousResponse) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *AnonymousResponse) GetIsTorExitNode() bool {
	if x != nil {
		return x.IsTorExitNode
	}
	return false
}

func (x *AnonymousResponse) GetFeatureSupport() bool {
	if x != nil {
		return x.FeatureSupport
	}
	return false
}

// CityInfo는 도시 정보를 표현하는 메시지입니다
type CityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeonameId     uint32                 `protobuf:"varint,1,opt,name=geoname_id,json=geonameId,proto3" json:"geoname_id,omitempty"`
	Names         map[string]string      `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityInfo) Reset() {
	*x = CityInfo{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityInfo) ProtoMessage() {}

func (x *CityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityInfo.ProtoReflect.Descriptor instead.
func (*CityInfo) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{6}
}

func (x *CityInfo) GetGeonameId() uint32 {
	if x != nil {
		return x.GeonameId
	}
	return 0
}

func (x *CityInfo) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

// CountryInfo는 국가 정보를 표현하는 메시지입니다
type CountryInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GeonameId         uint32                 `protobuf:"varint,1,opt,name=geoname_id,json=geonameId,proto3" json:"geoname_id,omitempty"`
	IsInEuropeanUnion bool                   `protobuf:"varint,2,opt,name=is_in_european_union,json=isInEuropeanUnion,proto3" json:"is_in_european_union,omitempty"`
	IsoCode           string                 `protobuf:"bytes,3,opt,name=iso_code,json=isoCode,proto3" json:"iso_code,omitempty"`
	Names             map[string]string      `protobuf:"bytes,4,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CountryInfo) Reset() {
	*x = CountryInfo{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryInfo) ProtoMessage() {}

func (x *CountryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryInfo.ProtoReflect.Descriptor instead.
func (*CountryInfo) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{7}
}

func (x *CountryInfo) GetGeonameId() uint32 {
	if x != nil {
		return x.GeonameId
	}
	return 0
}

func (x *CountryInfo) GetIsInEuropeanUnion() bool {
	if x != nil {
		return x.IsInEuropeanUnion
	}
	return false
}

func (x *CountryInfo) GetIsoCode() string {
	if x != nil {
		return x.IsoCode
	}
	return ""
}

func (x *CountryInfo) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

// ContinentInfo는 대륙 정보를 표현하는 메시지입니다
type ContinentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	GeonameId     uint32                 `protobuf:"varint,2,opt,name=geoname_id,json=geonameId,proto3" json:"geoname_id,omitempty"`
	Names         map[string]string      `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinentInfo) Reset() {
	*x = ContinentInfo{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinentInfo) ProtoMessage() {}

func (x *ContinentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinentInfo.ProtoReflect.Descriptor instead.
func (*ContinentInfo) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{8}
}

func (x *ContinentInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ContinentInfo) GetGeonameId() uint32 {
	if x != nil {
		return x.GeonameId
	}
	return 0
}

func (x *ContinentInfo) GetNames() map[string]string {
	if x != nil {
		return x.Names
	}
	return nil
}

// LocationInfo는 위치 정보를 표현하는 메시지입니다
type LocationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	TimeZone      string                 `protobuf:"bytes,3,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationInfo) Reset() {
	*x = LocationInfo{}
	mi := &file_proto_geo_v1_geo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationInfo) ProtoMessage() {}

func (x *LocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geo_v1_geo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationInfo.ProtoReflect.Descriptor instead.
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return file_proto_geo_v1_geo_proto_rawDescGZIP(), []int{9}
}

func (x *LocationInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationInfo) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

var File_proto_geo_v1_geo_proto protoreflect.FileDescriptor

const file_proto_geo_v1_geo_proto_rawDesc = "" +
	"\n" +
	"\x16proto/geo/v1/geo.proto\x12\x03geo\"\x1b\n" +
	"\tIpRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xbd\x03\n" +
	"\x0fGeoDataResponse\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x04 \x01(\tR\vcountryName\x12%\n" +
	"\x0econtinent_code\x18\x05 \x01(\tR\rcontinentCode\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x1b\n" +
	"\ttime_zone\x18\b \x01(\tR\btimeZone\x12\x10\n" +
	"\x03asn\x18\t \x01(\rR\x03asn\x12\x10\n" +
	"\x03isp\x18\n" +
	" \x01(\tR\x03isp\x12\x19\n" +
	"\bis_valid\x18\v \x01(\bR\aisValid\x12!\n" +
	"\fis_anonymous\x18\f \x01(\bR\visAnonymous\x12(\n" +
	"\x10is_anonymous_vpn\x18\r \x01(\bR\x0eisAnonymousVpn\x12'\n" +
	"\x10is_tor_exit_node\x18\x0e \x01(\bR\risTorExitNode\"\xbe\x01\n" +
	"\fCityResponse\x12!\n" +
	"\x04city\x18\x01 \x01(\v2\r.geo.CityInfoR\x04city\x12*\n" +
	"\acountry\x18\x02 \x01(\v2\x10.geo.CountryInfoR\acountry\x120\n" +
	"\tcontinent\x18\x03 \x01(\v2\x12.geo.ContinentInfoR\tcontinent\x12-\n" +
	"\blocation\x18\x04 \x01(\v2\x11.geo.LocationInfoR\blocation\"o\n" +
	"\x0fCountryResponse\x12*\n" +
	"\acountry\x18\x01 \x01(\v2\x10.geo.CountryInfoR\acountry\x120\n" +
	"\tcontinent\x18\x02 \x01(\v2\x12.geo.ContinentInfoR\tcontinent\"\x8d\x01\n" +
	"\vASNResponse\x128\n" +
	"\x18autonomous_system_number\x18\x01 \x01(\rR\x16autonomousSystemNumber\x12D\n" +
	"\x1eautonomous_system_organization\x18\x02 \x01(\tR\x1cautonomousSystemOrganization\"\x88\x01\n" +
	"\x11AnonymousResponse\x12!\n" +
	"\fis_anonymous\x18\x01 \x01(\bR\visAnonymous\x12'\n" +
	"\x10is_tor_exit_node\x18\x02 \x01(\bR\risTorExitNode\x12'\n" +
	"\x0ffeature_support\x18\x03 \x01(\bR\x0efeatureSupport\"\x93\x01\n" +
	"\bCityInfo\x12\x1d\n" +
	"\n" +
	"geoname_id\x18\x01 \x01(\rR\tgeonameId\x12.\n" +
	"\x05names\x18\x02 \x03(\v2\x18.geo.CityInfo.NamesEntryR\x05names\x1a8\n" +
	"\n" +
	"NamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x01\n" +
	"\vCountryInfo\x12\x1d\n" +
	"\n" +
	"geoname_id\x18\x01 \x01(\rR\tgeonameId\x12/\n" +
	"\x14is_in_european_union\x18\x02 \x01(\bR\x11isInEuropeanUnion\x12\x19\n" +
	"\biso_code\x18\x03 \x01(\tR\aisoCode\x121\n" +
	"\x05names\x18\x04 \x03(\v2\x1b.geo.CountryInfo.NamesEntryR\x05names\x1a8\n" +
	"\n" +
	"NamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\rContinentInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"geoname_id\x18\x02 \x01(\rR\tgeonameId\x123\n" +
	"\x05names\x18\x03 \x03(\v2\x1d.geo.ContinentInfo.NamesEntryR\x05names\x1a8\n" +
	"\n" +
	"NamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\fLocationInfo\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\ttime_zone\x18\x03 \x01(\tR\btimeZone2\xa0\x02\n" +
	"\n" +
	"GeoService\x124\n" +
	"\n" +
	"GetGeoData\x12\x0e.geo.IpRequest\x1a\x14.geo.GeoDataResponse\"\x00\x122\n" +
	"\vGetCityInfo\x12\x0e.geo.IpRequest\x1a\x11.geo.CityResponse\"\x00\x128\n" +
	"\x0eGetCountryInfo\x12\x0e.geo.IpRequest\x1a\x14.geo.CountryResponse\"\x00\x120\n" +
	"\n" +
	"GetASNInfo\x12\x0e.geo.IpRequest\x1a\x10.geo.ASNResponse\"\x00\x12<\n" +
	"\x10CheckAnonymousIP\x12\x0e.geo.IpRequest\x1a\x16.geo.AnonymousResponse\"\x00BaZ_github.com/wekeepgrowing/semo-backend-monorepo/services/geo/internal/adapter/handler/grpc/protob\x06proto3"

var (
	file_proto_geo_v1_geo_proto_rawDescOnce sync.Once
	file_proto_geo_v1_geo_proto_rawDescData []byte
)

func file_proto_geo_v1_geo_proto_rawDescGZIP() []byte {
	file_proto_geo_v1_geo_proto_rawDescOnce.Do(func() {
		file_proto_geo_v1_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_geo_v1_geo_proto_rawDesc), len(file_proto_geo_v1_geo_proto_rawDesc)))
	})
	return file_proto_geo_v1_geo_proto_rawDescData
}

var file_proto_geo_v1_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_geo_v1_geo_proto_goTypes = []any{
	(*IpRequest)(nil),         // 0: geo.IpRequest
	(*GeoDataResponse)(nil),   // 1: geo.GeoDataResponse
	(*CityResponse)(nil),      // 2: geo.CityResponse
	(*CountryResponse)(nil),   // 3: geo.CountryResponse
	(*ASNResponse)(nil),       // 4: geo.ASNResponse
	(*AnonymousResponse)(nil), // 5: geo.AnonymousResponse
	(*CityInfo)(nil),          // 6: geo.CityInfo
	(*CountryInfo)(nil),       // 7: geo.CountryInfo
	(*ContinentInfo)(nil),     // 8: geo.ContinentInfo
	(*LocationInfo)(nil),      // 9: geo.LocationInfo
	nil,                       // 10: geo.CityInfo.NamesEntry
	nil,                       // 11: geo.CountryInfo.NamesEntry
	nil,                       // 12: geo.ContinentInfo.NamesEntry
}
var file_proto_geo_v1_geo_proto_depIdxs = []int32{
	6,  // 0: geo.CityResponse.city:type_name -> geo.CityInfo
	7,  // 1: geo.CityResponse.country:type_name -> geo.CountryInfo
	8,  // 2: geo.CityResponse.continent:type_name -> geo.ContinentInfo
	9,  // 3: geo.CityResponse.location:type_name -> geo.LocationInfo
	7,  // 4: geo.CountryResponse.country:type_name -> geo.CountryInfo
	8,  // 5: geo.CountryResponse.continent:type_name -> geo.ContinentInfo
	10, // 6: geo.CityInfo.names:type_name -> geo.CityInfo.NamesEntry
	11, // 7: geo.CountryInfo.names:type_name -> geo.CountryInfo.NamesEntry
	12, // 8: geo.ContinentInfo.names:type_name -> geo.ContinentInfo.NamesEntry
	0,  // 9: geo.GeoService.GetGeoData:input_type -> geo.IpRequest
	0,  // 10: geo.GeoService.GetCityInfo:input_type -> geo.IpRequest
	0,  // 11: geo.GeoService.GetCountryInfo:input_type -> geo.IpRequest
	0,  // 12: geo.GeoService.GetASNInfo:input_type -> geo.IpRequest
	0,  // 13: geo.GeoService.CheckAnonymousIP:input_type -> geo.IpRequest
	1,  // 14: geo.GeoService.GetGeoData:output_type -> geo.GeoDataResponse
	2,  // 15: geo.GeoService.GetCityInfo:output_type -> geo.CityResponse
	3,  // 16: geo.GeoService.GetCountryInfo:output_type -> geo.CountryResponse
	4,  // 17: geo.GeoService.GetASNInfo:output_type -> geo.ASNResponse
	5,  // 18: geo.GeoService.CheckAnonymousIP:output_type -> geo.AnonymousResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_geo_v1_geo_proto_init() }
func file_proto_geo_v1_geo_proto_init() {
	if File_proto_geo_v1_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_geo_v1_geo_proto_rawDesc), len(file_proto_geo_v1_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_geo_v1_geo_proto_goTypes,
		DependencyIndexes: file_proto_geo_v1_geo_proto_depIdxs,
		MessageInfos:      file_proto_geo_v1_geo_proto_msgTypes,
	}.Build()
	File_proto_geo_v1_geo_proto = out.File
	file_proto_geo_v1_geo_proto_goTypes = nil
	file_proto_geo_v1_geo_proto_depIdxs = nil
}
