// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/geo/v1/geo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoService_GetGeoData_FullMethodName       = "/geo.GeoService/GetGeoData"
	GeoService_GetCityInfo_FullMethodName      = "/geo.GeoService/GetCityInfo"
	GeoService_GetCountryInfo_FullMethodName   = "/geo.GeoService/GetCountryInfo"
	GeoService_GetASNInfo_FullMethodName       = "/geo.GeoService/GetASNInfo"
	GeoService_CheckAnonymousIP_FullMethodName = "/geo.GeoService/CheckAnonymousIP"
)

// GeoServiceClient is the client API for GeoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GeoService는 IP 주소에 대한 지리적 정보를 제공하는 서비스입니다
type GeoServiceClient interface {
	// GetGeoData는 IP 주소에 대한 종합적인 지리 정보를 반환합니다
	GetGeoData(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*GeoDataResponse, error)
	// GetCityInfo는 IP 주소에 대한 도시 정보를 반환합니다
	GetCityInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*CityResponse, error)
	// GetCountryInfo는 IP 주소에 대한 국가 정보를 반환합니다
	GetCountryInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*CountryResponse, error)
	// GetASNInfo는 IP 주소에 대한 ASN 정보를 반환합니다
	GetASNInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*ASNResponse, error)
	// CheckAnonymousIP는 IP 주소가 익명 프록시인지 확인합니다
	CheckAnonymousIP(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*AnonymousResponse, error)
}

type geoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoServiceClient(cc grpc.ClientConnInterface) GeoServiceClient {
	return &geoServiceClient{cc}
}

func (c *geoServiceClient) GetGeoData(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*GeoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoDataResponse)
	err := c.cc.Invoke(ctx, GeoService_GetGeoData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoServiceClient) GetCityInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*CityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CityResponse)
	err := c.cc.Invoke(ctx, GeoService_GetCityInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoServiceClient) GetCountryInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*CountryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountryResponse)
	err := c.cc.Invoke(ctx, GeoService_GetCountryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoServiceClient) GetASNInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*ASNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ASNResponse)
	err := c.cc.Invoke(ctx, GeoService_GetASNInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoServiceClient) CheckAnonymousIP(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*AnonymousResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnonymousResponse)
	err := c.cc.Invoke(ctx, GeoService_CheckAnonymousIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoServiceServer is the server API for GeoService service.
// All implementations must embed UnimplementedGeoServiceServer
// for forward compatibility.
//
// GeoService는 IP 주소에 대한 지리적 정보를 제공하는 서비스입니다
type GeoServiceServer interface {
	// GetGeoData는 IP 주소에 대한 종합적인 지리 정보를 반환합니다
	GetGeoData(context.Context, *IpRequest) (*GeoDataResponse, error)
	// GetCityInfo는 IP 주소에 대한 도시 정보를 반환합니다
	GetCityInfo(context.Context, *IpRequest) (*CityResponse, error)
	// GetCountryInfo는 IP 주소에 대한 국가 정보를 반환합니다
	GetCountryInfo(context.Context, *IpRequest) (*CountryResponse, error)
	// GetASNInfo는 IP 주소에 대한 ASN 정보를 반환합니다
	GetASNInfo(context.Context, *IpRequest) (*ASNResponse, error)
	// CheckAnonymousIP는 IP 주소가 익명 프록시인지 확인합니다
	CheckAnonymousIP(context.Context, *IpRequest) (*AnonymousResponse, error)
	mustEmbedUnimplementedGeoServiceServer()
}

// UnimplementedGeoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoServiceServer struct{}

func (UnimplementedGeoServiceServer) GetGeoData(context.Context, *IpRequest) (*GeoDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeoData not implemented")
}
func (UnimplementedGeoServiceServer) GetCityInfo(context.Context, *IpRequest) (*CityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCityInfo not implemented")
}
func (UnimplementedGeoServiceServer) GetCountryInfo(context.Context, *IpRequest) (*CountryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountryInfo not implemented")
}
func (UnimplementedGeoServiceServer) GetASNInfo(context.Context, *IpRequest) (*ASNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetASNInfo not implemented")
}
func (UnimplementedGeoServiceServer) CheckAnonymousIP(context.Context, *IpRequest) (*AnonymousResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAnonymousIP not implemented")
}
func (UnimplementedGeoServiceServer) mustEmbedUnimplementedGeoServiceServer() {}
func (UnimplementedGeoServiceServer) testEmbeddedByValue()                    {}

// UnsafeGeoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoServiceServer will
// result in compilation errors.
type UnsafeGeoServiceServer interface {
	mustEmbedUnimplementedGeoServiceServer()
}

func RegisterGeoServiceServer(s grpc.ServiceRegistrar, srv GeoServiceServer) {
	// If the following call pancis, it indicates UnimplementedGeoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoService_ServiceDesc, srv)
}

func _GeoService_GetGeoData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServiceServer).GetGeoData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoService_GetGeoData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServiceServer).GetGeoData(ctx, req.(*IpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoService_GetCityInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServiceServer).GetCityInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoService_GetCityInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServiceServer).GetCityInfo(ctx, req.(*IpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoService_GetCountryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServiceServer).GetCountryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoService_GetCountryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServiceServer).GetCountryInfo(ctx, req.(*IpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoService_GetASNInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServiceServer).GetASNInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoService_GetASNInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServiceServer).GetASNInfo(ctx, req.(*IpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoService_CheckAnonymousIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServiceServer).CheckAnonymousIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoService_CheckAnonymousIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServiceServer).CheckAnonymousIP(ctx, req.(*IpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoService_ServiceDesc is the grpc.ServiceDesc for GeoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo.GeoService",
	HandlerType: (*GeoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGeoData",
			Handler:    _GeoService_GetGeoData_Handler,
		},
		{
			MethodName: "GetCityInfo",
			Handler:    _GeoService_GetCityInfo_Handler,
		},
		{
			MethodName: "GetCountryInfo",
			Handler:    _GeoService_GetCountryInfo_Handler,
		},
		{
			MethodName: "GetASNInfo",
			Handler:    _GeoService_GetASNInfo_Handler,
		},
		{
			MethodName: "CheckAnonymousIP",
			Handler:    _GeoService_CheckAnonymousIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/geo/v1/geo.proto",
}
