// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/geolite/geolite.proto

package geolite

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoLiteService_GetGeoIP_FullMethodName = "/geolite.GeoLiteService/GetGeoIP"
)

// GeoLiteServiceClient is the client API for GeoLiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC 서비스 정의
type GeoLiteServiceClient interface {
	GetGeoIP(ctx context.Context, in *GeoIPRequest, opts ...grpc.CallOption) (*GeoIPResponse, error)
}

type geoLiteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoLiteServiceClient(cc grpc.ClientConnInterface) GeoLiteServiceClient {
	return &geoLiteServiceClient{cc}
}

func (c *geoLiteServiceClient) GetGeoIP(ctx context.Context, in *GeoIPRequest, opts ...grpc.CallOption) (*GeoIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoIPResponse)
	err := c.cc.Invoke(ctx, GeoLiteService_GetGeoIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoLiteServiceServer is the server API for GeoLiteService service.
// All implementations must embed UnimplementedGeoLiteServiceServer
// for forward compatibility.
//
// gRPC 서비스 정의
type GeoLiteServiceServer interface {
	GetGeoIP(context.Context, *GeoIPRequest) (*GeoIPResponse, error)
	mustEmbedUnimplementedGeoLiteServiceServer()
}

// UnimplementedGeoLiteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoLiteServiceServer struct{}

func (UnimplementedGeoLiteServiceServer) GetGeoIP(context.Context, *GeoIPRequest) (*GeoIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeoIP not implemented")
}
func (UnimplementedGeoLiteServiceServer) mustEmbedUnimplementedGeoLiteServiceServer() {}
func (UnimplementedGeoLiteServiceServer) testEmbeddedByValue()                        {}

// UnsafeGeoLiteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoLiteServiceServer will
// result in compilation errors.
type UnsafeGeoLiteServiceServer interface {
	mustEmbedUnimplementedGeoLiteServiceServer()
}

func RegisterGeoLiteServiceServer(s grpc.ServiceRegistrar, srv GeoLiteServiceServer) {
	// If the following call pancis, it indicates UnimplementedGeoLiteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoLiteService_ServiceDesc, srv)
}

func _GeoLiteService_GetGeoIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLiteServiceServer).GetGeoIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLiteService_GetGeoIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLiteServiceServer).GetGeoIP(ctx, req.(*GeoIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoLiteService_ServiceDesc is the grpc.ServiceDesc for GeoLiteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoLiteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geolite.GeoLiteService",
	HandlerType: (*GeoLiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGeoIP",
			Handler:    _GeoLiteService_GetGeoIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/geolite/geolite.proto",
}
