// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: proto/geolite/geolite.proto

package geolite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IP 요청 메시지
type GeoIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // IP 주소
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoIPRequest) Reset() {
	*x = GeoIPRequest{}
	mi := &file_proto_geolite_geolite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoIPRequest) ProtoMessage() {}

func (x *GeoIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geolite_geolite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoIPRequest.ProtoReflect.Descriptor instead.
func (*GeoIPRequest) Descriptor() ([]byte, []int) {
	return file_proto_geolite_geolite_proto_rawDescGZIP(), []int{0}
}

func (x *GeoIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// IP 조회 결과 메시지
type GeoIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryIso    string                 `protobuf:"bytes,1,opt,name=country_iso,json=countryIso,proto3" json:"country_iso,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	TimeZone      string                 `protobuf:"bytes,4,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoIPResponse) Reset() {
	*x = GeoIPResponse{}
	mi := &file_proto_geolite_geolite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoIPResponse) ProtoMessage() {}

func (x *GeoIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geolite_geolite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoIPResponse.ProtoReflect.Descriptor instead.
func (*GeoIPResponse) Descriptor() ([]byte, []int) {
	return file_proto_geolite_geolite_proto_rawDescGZIP(), []int{1}
}

func (x *GeoIPResponse) GetCountryIso() string {
	if x != nil {
		return x.CountryIso
	}
	return ""
}

func (x *GeoIPResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoIPResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoIPResponse) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *GeoIPResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoIPResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_proto_geolite_geolite_proto protoreflect.FileDescriptor

var file_proto_geolite_geolite_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x6c, 0x69, 0x74, 0x65, 0x2f,
	0x67, 0x65, 0x6f, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67,
	0x65, 0x6f, 0x6c, 0x69, 0x74, 0x65, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x65, 0x6f, 0x49, 0x50, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0xb5, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x6f, 0x49, 0x50,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x5f, 0x69, 0x73, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x73, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65,
	0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x32, 0x4b,
	0x0a, 0x0e, 0x47, 0x65, 0x6f, 0x4c, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x49, 0x50, 0x12, 0x15, 0x2e, 0x67,
	0x65, 0x6f, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x6f, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x65, 0x6f, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x47, 0x65,
	0x6f, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x65, 0x6f, 0x6c, 0x69, 0x74, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x6c, 0x69, 0x74, 0x65, 0x3b, 0x67, 0x65, 0x6f, 0x6c,
	0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_geolite_geolite_proto_rawDescOnce sync.Once
	file_proto_geolite_geolite_proto_rawDescData []byte
)

func file_proto_geolite_geolite_proto_rawDescGZIP() []byte {
	file_proto_geolite_geolite_proto_rawDescOnce.Do(func() {
		file_proto_geolite_geolite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_geolite_geolite_proto_rawDesc), len(file_proto_geolite_geolite_proto_rawDesc)))
	})
	return file_proto_geolite_geolite_proto_rawDescData
}

var file_proto_geolite_geolite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_geolite_geolite_proto_goTypes = []any{
	(*GeoIPRequest)(nil),  // 0: geolite.GeoIPRequest
	(*GeoIPResponse)(nil), // 1: geolite.GeoIPResponse
}
var file_proto_geolite_geolite_proto_depIdxs = []int32{
	0, // 0: geolite.GeoLiteService.GetGeoIP:input_type -> geolite.GeoIPRequest
	1, // 1: geolite.GeoLiteService.GetGeoIP:output_type -> geolite.GeoIPResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_geolite_geolite_proto_init() }
func file_proto_geolite_geolite_proto_init() {
	if File_proto_geolite_geolite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_geolite_geolite_proto_rawDesc), len(file_proto_geolite_geolite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_geolite_geolite_proto_goTypes,
		DependencyIndexes: file_proto_geolite_geolite_proto_depIdxs,
		MessageInfos:      file_proto_geolite_geolite_proto_msgTypes,
	}.Build()
	File_proto_geolite_geolite_proto = out.File
	file_proto_geolite_geolite_proto_goTypes = nil
	file_proto_geolite_geolite_proto_depIdxs = nil
}
