-- Migration: Create toss_webhook_events table
-- This file is for reference - the table will be created automatically by GORM AutoMigrate
-- Run this manually only if you need to create the table without running the application

CREATE TABLE IF NOT EXISTS toss_webhook_events (
    -- Primary Key
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- TossPayments webhook identifier
    toss_event_id VARCHAR(255) UNIQUE,  -- Unique ID for deduplication
    
    -- Event information
    event_type VARCHAR(100) NOT NULL,   -- DEPOSIT_CALLBACK, PAYMENT_STATUS_CHANGED, etc.
    event_status VARCHAR(50),           -- DONE, CANCELED, WAITING_FOR_DEPOSIT, etc.
    
    -- Processing status (uses existing webhook_status enum)
    processing_status webhook_status NOT NULL DEFAULT 'pending', -- pending, processing, completed, failed
    processed_at TIMESTAMP,
    
    -- Payment related keys
    payment_key VARCHAR(200),           -- Payment unique key
    order_id VARCHAR(200),              -- Order ID
    transaction_key VARCHAR(200),       -- Transaction key
    secret VARCHAR(200),                -- Virtual account secret (for verification)
    
    -- Event data (uses existing JSONB type)
    event_data JSONB NOT NULL,          -- Full webhook payload
    
    -- Retry related
    retry_count INTEGER DEFAULT 0,
    last_error TEXT,
    next_retry_at TIMESTAMP,
    
    -- Metadata
    ip_address VARCHAR(45),             -- Webhook sender IP
    user_agent TEXT,                    -- User-Agent header
    
    -- Timestamps
    toss_created_at TIMESTAMP NOT NULL, -- Time created by TossPayments
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_toss_webhook_event_type ON toss_webhook_events (event_type);
CREATE INDEX IF NOT EXISTS idx_toss_webhook_event_status ON toss_webhook_events (event_status);
CREATE INDEX IF NOT EXISTS idx_toss_webhook_processing_status ON toss_webhook_events (processing_status);
CREATE INDEX IF NOT EXISTS idx_toss_webhook_payment_key ON toss_webhook_events (payment_key);
CREATE INDEX IF NOT EXISTS idx_toss_webhook_order_id ON toss_webhook_events (order_id);
CREATE INDEX IF NOT EXISTS idx_toss_webhook_created_at ON toss_webhook_events (created_at);
CREATE INDEX IF NOT EXISTS idx_toss_webhook_toss_created_at ON toss_webhook_events (toss_created_at);
CREATE INDEX IF NOT EXISTS idx_toss_webhook_unprocessed ON toss_webhook_events (processing_status, next_retry_at) 
    WHERE processing_status IN ('pending', 'failed');

-- Add updated_at trigger (if you have a generic updated_at trigger function)
-- CREATE TRIGGER update_toss_webhook_events_updated_at 
--     BEFORE UPDATE ON toss_webhook_events 
--     FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();