-- Billing keys table for storing encrypted billing keys
CREATE TABLE IF NOT EXISTS billing_keys (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    universal_id UUID NOT NULL,
    customer_key VARCHAR(300) NOT NULL UNIQUE,
    encrypted_billing_key TEXT NOT NULL,
    encryption_iv TEXT NOT NULL,
    card_last_four VARCHAR(4),
    card_company VARCHAR(50),
    card_type VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deactivated_at TIMESTAMP
);

CREATE INDEX idx_billing_keys_universal_id ON billing_keys(universal_id);
CREATE INDEX idx_billing_keys_customer_key ON billing_keys(customer_key);
CREATE INDEX idx_billing_keys_active ON billing_keys(is_active) WHERE is_active = TRUE;
