-- Billing key access logs for audit trail (2-year retention per privacy law)
CREATE TABLE IF NOT EXISTS billing_key_access_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    billing_key_id BIGINT NOT NULL,
    access_type VARCHAR(50) NOT NULL,
    accessor_id VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent TEXT,
    purpose VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_access_logs_billing_key
        FOREIGN KEY (billing_key_id) REFERENCES billing_keys(id)
);

CREATE INDEX idx_billing_key_access_logs_billing_key_id ON billing_key_access_logs(billing_key_id);
CREATE INDEX idx_billing_key_access_logs_created_at ON billing_key_access_logs(created_at);
