-- Scheduled payments for recurring billing
CREATE TABLE IF NOT EXISTS scheduled_payments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subscription_id BIGINT NOT NULL,
    billing_key_id BIGINT NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    amount BIGINT NOT NULL,
    currency VARCHAR(3) DEFAULT 'KRW',
    order_name VARCHAR(255),
    status VARCHAR(20) DEFAULT 'pending',
    attempt_count INT DEFAULT 0,
    last_attempt_at TIMESTAMP,
    last_error TEXT,
    next_retry_at TIMESTAMP,
    completed_at TIMESTAMP,
    payment_id BIGINT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_scheduled_payments_billing_key
        FOREIGN KEY (billing_key_id) REFERENCES billing_keys(id),
    CONSTRAINT fk_scheduled_payments_subscription
        FOREIGN KEY (subscription_id) REFERENCES subscriptions(id)
);

CREATE INDEX idx_scheduled_payments_scheduled_at ON scheduled_payments(scheduled_at);
CREATE INDEX idx_scheduled_payments_status ON scheduled_payments(status);
CREATE INDEX idx_scheduled_payments_due ON scheduled_payments(status, scheduled_at)
    WHERE status IN ('pending', 'failed');
