// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/public_key.proto

package publickey

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicKeyService_GetPublicKey_FullMethodName = "/publickey.PublicKeyService/GetPublicKey"
)

// PublicKeyServiceClient is the client API for PublicKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ECDSA 공개키를 배포하는 서비스 정의
type PublicKeyServiceClient interface {
	GetPublicKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PublicKeyResponse, error)
}

type publicKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicKeyServiceClient(cc grpc.ClientConnInterface) PublicKeyServiceClient {
	return &publicKeyServiceClient{cc}
}

func (c *publicKeyServiceClient) GetPublicKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, PublicKeyService_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicKeyServiceServer is the server API for PublicKeyService service.
// All implementations must embed UnimplementedPublicKeyServiceServer
// for forward compatibility.
//
// ECDSA 공개키를 배포하는 서비스 정의
type PublicKeyServiceServer interface {
	GetPublicKey(context.Context, *Empty) (*PublicKeyResponse, error)
	mustEmbedUnimplementedPublicKeyServiceServer()
}

// UnimplementedPublicKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicKeyServiceServer struct{}

func (UnimplementedPublicKeyServiceServer) GetPublicKey(context.Context, *Empty) (*PublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedPublicKeyServiceServer) mustEmbedUnimplementedPublicKeyServiceServer() {}
func (UnimplementedPublicKeyServiceServer) testEmbeddedByValue()                          {}

// UnsafePublicKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicKeyServiceServer will
// result in compilation errors.
type UnsafePublicKeyServiceServer interface {
	mustEmbedUnimplementedPublicKeyServiceServer()
}

func RegisterPublicKeyServiceServer(s grpc.ServiceRegistrar, srv PublicKeyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPublicKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicKeyService_ServiceDesc, srv)
}

func _PublicKeyService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicKeyServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicKeyService_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicKeyServiceServer).GetPublicKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicKeyService_ServiceDesc is the grpc.ServiceDesc for PublicKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "publickey.PublicKeyService",
	HandlerType: (*PublicKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _PublicKeyService_GetPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/public_key.proto",
}
